name: Basic workflow develop

# trigger
# push on main branch
on:
  push:
    branches:
      - main
env:
  DOCKER_IMAGE: ${{ vars.DOCKERHUB_USERNAME }}/api-session13

jobs:
  # 1-unit test
    # checkout code
    # run unit test
  # run-unit-test-job:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: clone source code to runner 
  #       uses: actions/checkout@v5

  #     - name: install dependecies
  #       run:  npm i

  #     - name: run unit test
  #       run: npm run test

  # # 2-build docker image and push
  #   # checkout code 
  #   # build docker image
  #   # tag docker image with version
  #   # login to dockerhub
  #   # push docker image
  # build-docker-image-and-push:
  #   needs: run-unit-test-job
  #   runs-on: ubuntu-latest
  #   steps:
  #       - name: clone source code to runner
  #         uses: actions/checkout@v5

  #       - name: build docker image
  #         run: docker build -t ${{ env.DOCKER_IMAGE}} .

  #       - name: tag docker image
  #         run: docker tag ${{ env.DOCKER_IMAGE}} ${{ env.DOCKER_IMAGE}}:v${{ github.run_number }}

  #       - name: show docker images
  #         run: docker images

  #       - name: show docker username and acces-token
  #         run: |
  #           echo ${{ vars.DOCKERHUB_USERNAME }}
  #           echo ${{ secrets.DOCKERHUB_TOKEN }}

  #       - name: Login to Docker Hub
  #         uses: docker/login-action@v3
  #         with:
  #           username: ${{ vars.DOCKERHUB_USERNAME }}
  #           password: ${{ secrets.DOCKERHUB_TOKEN }}
  #       - name: push image to dockerhub
  #         run: docker push ${{ env.DOCKER_IMAGE}}:v${{ github.run_number }}

  #       - name: push latest image to dockerhub
  #         run: docker push ${{ env.DOCKER_IMAGE}}:latest
  # 3-deploy to vps
    # ssh connecct to vps
    # pull docker image
    # run docker container
    deploy-to-vps:
      runs-on: ubuntu-latest
      # needs: build-docker-image-and-push
      steps:
        - name: Execute remote SSH commands using password
          uses: appleboy/ssh-action@v1
          with:
            host: ${{ secrets.VPS_HOST }}
            username: user
            password: ${{ secrets.VPS_PASSWORD }}
            script: whoami