name: Basic workflow develop

# trigger
# push on main branch
on:
  push:
    branches:
      - main


jobs:
  # 1-unit test
    # checkout code
    # run unit test
  run-unit-test-job:
    runs-on: ubuntu-latest
    steps:
      - name: clone source code to runner 
        uses: actions/checkout@v5

      - name: install dependecies
        run:  npm i

      - name: run unit test
        run: npm run test

  # 2-build docker image and push
    # checkout code 
    # build docker image
    # tag docker image with version
    # login to dockerhub
    # push docker image
  build-docker-image-and-push:
    needs: run-unit-test-job
    runs-on: ubuntu-latest
    steps:
        - name: clone source code to runner
          uses: actions/checkout@v5

        - name: build docker image
          run: docker build -t marwenaddinn/api-session13 .

        - name: tag docker image
          run: docker tag marwenaddinn/api-session13 marwenaddinn/api-session13:v2

        - name: show docker images
          run: docker images

        - name: show docker username and acces-token
          run: |
            echo ${{ vars.DOCKERHUB_USERNAME }}
            echo ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ vars.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
  # 3-deploy to vps
    # ssh connecct to vps
    # pull docker image
    # run docker container