name: Basic workflow develop

# trigger
# push on main branch
on:
  push:
    branches:
      - main


jobs:
  # 1-unit test
    # checkout code
    # run unit test
  run-unit-test-job:
    runs-on: ubuntu-latest
    steps:
      - name: clone source code to runner 
        uses: actions/checkout@v5

      - name: install dependecies
        run:  npm i

      - name: run unit test
        run: npm run test

  # 2-build docker image and push
    # checkout code 
    # build docker image
    # tag docker image with version
    # login to dockerhub
    # push docker image
  build-docker-image-and-push:
    needs: run-unit-test-job
    runs-on: ubuntu-latest
    steps:
        - name: clone source code to runner
          uses: actions/checkout@v5

  # 3-deploy to vps
    # ssh connecct to vps
    # pull docker image
    # run docker container